# Generated by Django 5.0.4 on 2024-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('in_production', 'In Production'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='payment_pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantityRequested', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('profits', models.IntegerField()),
            ],
        ),
    ]
