# Generated by Django 5.0.4 on 2024-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profits',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('cooking', 'Cooking'), ('packaging', 'Packaging'), ('labelling', 'Labelling'), ('ready', 'Ready')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.product'),
        ),
    ]
