# Generated by Django 5.0.4 on 2024-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_paid_order_is_paid_remove_order_profits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(choices=[('frambuesa', 'Frambuesa'), ('zarzamora', 'Zarzamora'), ('fresa', 'Fresa'), ('mango', 'Mango'), ('mora azul', 'Mora azul')], default='frambuesa', max_length=20),
        ),
    ]
