# Generated by Django 5.0.4 on 2024-05-11 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_company_name_alter_client_email_and_more'),
        ('orders', '0004_rename_products_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client'),
            preserve_default=False,
        ),
    ]
